### ISSUE TITLE
Please export LengthEncoderFunction and LengthDecoderFunction

### ISSUE THREAD

**Issue by paralin** [alanshaw/it-length-prefixed#35]
These types are not exported in index.ts and are not accessible outside the module.

... this would make it easier to define custom encoders/decoders.

**Comment by achingbrain** [comment]
Thanks for opening this - these types are exported from the [index file](https://github.com/alanshaw/it-length-prefixed/blob/master/src/index.ts#L6-L13) as of `it-length-prefixed@8.x.x`.
